#' Plot Model Assessment Results
#'
#' @description
#' Creates a quantile–quantile plot comparing observed annual maximum streamflow (AMS)
#' data to quantile estimates from a fitted parametric model. The 1:1 line is drawn in 
#' black and the model estimates are plotted as semi‐transparent red points.
#'
#' @param data Numeric; a vector of annual maximum streamflow data.
#'
#' @param assessment List; model assessment results generated by \link{model.assessment}.
#'
#' @return \code{ggplot}; a plot containing:
#'   - A black line for the theoretical 1:1 relationship between observed and model quantiles.
#'   - Red points marking the estimated quantiles against the observed quantiles.
#'
#' @examples
#' # Initialize example data, years, and params
#' data <- rnorm(n = 100, mean = 100, sd = 10)
#' years <- seq(from = 1901, to = 2000)
#' params <- c(100, 10)
#'
#' # Perform uncertainty analysis
#' uncertainty <- sb.uncertainty(data, years, "NOR", "L-moments")
#'
#' # Perform model assessment
#' assessment <- model.assessment(data, years, "NOR", params, uncertainty)
#'
#' # Generate a model assessment plot
#' assessment.plot(data, assessment)
#'
#' @import ggplot2
#' @export

assessment.plot <- function(data, assessment) {

	# Create a dataframe for the plot
	x <- data[order(data, decreasing = TRUE)]   
	df <- data.frame(x = x, y = x, estimates = assessment$estimates) 

	# Get labels for the plot
	x_label <- expression(Model ~ Quantiles ~ m^3/s)
	y_label <- expression(Observed ~ Quantiles ~ m^3/s)

	# Generate the plot
	p1 <- ggplot(data = df) +
		geom_line(aes(x = x, y = .data$y), linewidth = 1.1) + 
		geom_point(aes(x = x, y = .data$estimates), color = "red", size = 3, alpha = 0.5) + 
		labs(x = x_label, y = y_label, title = "Model Assessment")

	# Add theme and scales and return
	add_theme(add_scales(p1))

}
