#' Block-Bootstrap Mann-Kendall Test for Trend Detection
#'
#' Performs a bootstrapped version of the Mann-Kendall trend test to account
#' for serial correlation in annual maximum streamflow (AMS) data. The procedure
#' uses Spearman’s autocorrelation test to estimate the least insignificant lag, 
#' then applies a bootstrap procedure to obtain the empirical p-value and confidence 
#' bounds for the Mann-Kendall S-statistic.
#'
#' @param data Numeric; a vector of annual maximum streamflow data.
#'
#' @param alpha Numeric (1); the significance level (default is 0.05).
#'
#' @param n_sim Integer (1); the number of bootstrap simulations (default is 10000).
#'
#' @param quiet Logical (1); if FALSE, prints a summary of results (default is TRUE).
#'
#' @return List; the results of the test, including:
#' - `s.bootstrap`: Vector of bootstrapped test statistics used for plotting.
#' - `s.statistic`: The Mann-Kendall test statistic computed on the original series.
#' - `p.value`: Empirical two-sided p-value computed from the bootstrap distribution.
#' - `bounds`: Confidence interval bounds for the null distribution of the statistic.
#' - `reject`: Logical. TRUE if the null hypothesis was rejected at significance level alpha.
#' - `msg`: Character string summarizing the test result (printed if `quiet = FALSE`).
#'
#' @details
#' The block size for the bootstrap is selected as `least_lag + 1`, where `least_lag` 
#' is estimated using \link{spearman.test}. Each bootstrap sample is generated by 
#' resampling blocks of the original data  (without replacement) and computing the 
#' Mann-Kendall S-statistic. This procedure adjusts for autocorrelation in the data. 
#'
#' @seealso \link{mk.test}, \link{spearman.test}
#'
#' @examples
#' data <- rnorm(n = 100, mean = 100, sd = 10)
#' bbmk.test(data, n_sim = 1000)
#'
#' @importFrom stats quantile
#' @export

bbmk.test <- function(
  data,
  alpha = 0.05,
  n_sim = 10000,
  quiet = TRUE
) {

	# Assign a variable to the number of data points for convenience
	n <- length(data)

	# Compute least_lag and s_statistic from the Spearman and MK tests
	least_lag <- spearman.test(data, alpha)$least.lag
	s_statistic  <- mk.test(data, alpha)$s.statistic

	# Create blocks
	block_size <- least_lag + 1
	n_blocks <- ceiling(n / block_size)
	blocks <- split(data[1:(n_blocks * block_size)], rep(1:n_blocks, each = block_size))

	# Loop through the bootstrap in parallel
	bootstrap_list <- lapply(1:n_sim, function(i) { 

		# Sample blocks for this iteration
		sampled_blocks <- sample(blocks, n_blocks, replace = FALSE)
		sampled_data <- unlist(sampled_blocks, use.names = FALSE)

		# Compute the Mann-Kendall statistic for this iteration
		m <- outer(sampled_data, sampled_data, `-`)                   
  		s <- sum(sign(m[lower.tri(m)]), na.rm = TRUE)
		return (s)

	})

	bootstrap_results <- as.numeric(bootstrap_list)

	# Compute the p-value empirically using the bootstrap distribution
	p_value <- ifelse(
		s_statistic < 0, 
		2 * mean(s_statistic >= bootstrap_results),
		2 * mean(s_statistic <= bootstrap_results)
	)

	# Compute the CI bounds
	bounds <- quantile(bootstrap_results, c(alpha / 2, 1 - (alpha / 2)))

	# Determine whether we reject or fail to reject based on p_value and alpha
	reject <- (p_value <= alpha)

	# Print the results of the test
	msg <- test_message(
		"BBMK",
		reject,
		p_value,
		alpha,
		"evidence of a trend given the serial correlation.",
		"NO evidence of a trend given the serial correlation."
	)

	if (!quiet) message(msg)

	# Return the results as a list
	list(
		s.bootstrap = bootstrap_results,
		s.statistic = s_statistic,
		p.value = p_value,
		bounds = bounds,
		reject = reject,
		msg = msg
	)

}

