#' Plot Block‐Bootstrap Mann–Kendall Test Results
#'
#' @description
#' Generates a histogram of bootstrapped Mann–Kendall S‐statistics with vertical
#' lines indicating the observed S‐statistic and confidence bounds.
#'
#' @param results List; BB‐MK test results generated by \link{bbmk.test}.
#'
#' @return \code{ggplot}; A plot containing:
#'   - A gray histogram of the distribution of bootstrapped S‐statistics.
#'   - A red vertical line at the lower and upper confidence bounds.
#'   - A black vertical line at the observed S‐statistic.
#'
#' @examples
#' data <- rnorm(n = 100, mean = 100, sd = 10)
#' results <- bbmk.test(data, n_sim = 1000)
#' bbmk.plot(results)
#'
#' @import ggplot2
#' @export

bbmk.plot <- function(results) {

	p1 <- ggplot() +
		geom_histogram(
			aes(x = results$s.bootstrap, color = "gray"), 
			fill = "lightgray",
			bins = 30
		)  +
		geom_vline(aes(xintercept = results$bounds, color = "red"), linewidth = 1.2) + 
		geom_vline(aes(xintercept = results$s.statistic, color = "black"), linewidth = 1.2) + 
		labs(
			title = "Block-Bootstrap Mann-Kendall Test",
			x = "S-Statistic",
			y = "Frequency",
			color = "Legend"
		) + 
		scale_color_manual(
			values = c("gray" = "gray", "black" = "black", "red" = "red"),
			breaks = c("gray", "black", "red"),
			labels = c("Bootstrapped Statistics", "S-Statistic", "Confidence Bounds"),
		)

	# Return the plot with added theme
	add_theme(p1)

}
