#' Plot L-Moment Ratio Diagram with Sample and Candidate Distributions
#'
#' @description
#' Constructs an L-moment ratio plot (t4 vs. t3) showing the sample and log-sample
#' L-moment ratios alongside the theoretical locations for a set of candidate distributions.
#' Optionally highlights a small inset around the recommended distribution based on
#' either the L-distance or L-kurtosis metric.
#'
#' @param ams Numeric vector of observed annual maximum series (AMS) values.
#' @param metric Character string specifying the selection metric.  
#'   Must be one of:
#'   \itemize{
#'     \item \code{"L-distance"}: selects the distribution whose (t3, t4) location is closest
#'       in Euclidean distance to the sample point. See \code{\link{ld.selection}}.
#'     \item \code{"L-kurtosis"}: selects the distribution point with the same t3
#'       as the sample, minimizing |t4 difference|. See \code{\link{lk.selection}}.
#'     \item \code{"Z-statistic"}: selects the distribution by using a Kappa distribution
#'       and a parametric bootstrap. See \code{\link{z.selection}}.
#'   }
#'
#' @param results List of results from the model-selection procedure. Must contain:
#'   \describe{
#'     \item{\code{recommendation}}{Three-letter acronym of the selected distribution,  
#'       e.g. \code{"GEV"}, \code{"LP3"}.}
#'   }
#'  Generated by \code{\link{ld.selection}}, \code{\link{lk.selection}}, \code{\link{z.selection}}
#'
#' @return A \code{ggplot} object of the L-moment ratio diagram, with:
#'   \itemize{
#'     \item Lines for each 3-parameter distribution locus.
#'     \item Points for each 2-parameter distribution reference point.
#'     \item Sample and log-sample t3, t4 points.
#'     \item A legend mapping colors and shapes.
#'     \item If \code{metric} is \code{"L-distance"} or \code{"L-kurtosis"},
#'       an inset magnification of the neighborhood around the recommended point.
#'   }
#'
#' @import ggplot2
#' @importFrom grDevices pdf
#' @export

lmom.plot <- function(ams, metric, results) {

	# Create dataframes for the sample L-moments
	reg_sample_t3 = unname(samlmu(ams))[3]
	reg_sample_t4 = unname(samlmu(ams))[4]
	log_sample_t3 = unname(samlmu(log(ams)))[3]
	log_sample_t4 = unname(samlmu(log(ams)))[4]

	reg_lm <- data.frame(x = reg_sample_t3, y = reg_sample_t4)
	log_lm <- data.frame(x = log_sample_t4, y = log_sample_t4)

	# Generate a dataframe with the moments for each distribution
	dlm <- list()
	for (distribution in get.distributions()) {

		if (distribution$n_params == 2) {
			dlm[[distribution$name]] = data.frame(
				x = distribution$t3_t4[1],
				y = distribution$t3_t4[2]
			)
		}

		else {

			# Generate a sequence of parameter sets to pass to a 3-parameter distribution
			kappa_seq <- seq(distribution$kappa_lower, distribution$kappa_upper, 0.001)
			params <- lapply(kappa_seq, function(i) c(0, 1, i))

			# Get a vector of likelihood moment ratios for each parameterss set in params
			lmr <- lapply(params, function(p) suppressWarnings(distribution$lmr_function(p)))

			# Return the t3 and t4 values as a dataframe
			df = data.frame(x = sapply(lmr, `[`, 3), y = sapply(lmr, `[`, 4)) 
			df <- df[(df$x >= -1 & df$x <= 1), ]
			dlm[[distribution$name]] <- df

		}

	}

	# Initilaize the legend information
	labels <- c("Sample", "Log-Sample", "GEV/GUM", "GLO", "GNO/NOR/LNO", "PE3/LP3", "WEI", "GPA")
	colors <- c("#000000", "#000000", "#e69f00", "#56b4e9", "#009e73", "#0072b2", "#d55e00", "#cc79a7")
	shapes <- c(24, 15, 16, NA, 16, NA, NA, NA)

	# Define labels for the plot
	x_label <- expression("L-skewness (" * tau[3] * ")")
	y_label <- expression("L-kurtosis (" * tau[4] * ")")

	# Generate the plot
	p1 <- ggplot(mapping = aes(x = .data$x, y = .data$y)) +
		geom_line(data = dlm$GEV, aes(color = "3"), linewidth = 1) +
		geom_line(data = dlm$GLO, aes(color = "4"), linewidth = 1) +
		geom_line(data = dlm$GNO, aes(color = "5"), linewidth = 1) +
		geom_line(data = dlm$PE3, aes(color = "6"), linewidth = 1) +
		geom_line(data = dlm$WEI, aes(color = "7"), linewidth = 1) +
		geom_line(data = dlm$GPA, aes(color = "8"), linewidth = 1) +
		geom_point(data = dlm$GUM, aes(color = "3"), shape = 16, size = 4) +
		geom_point(data = dlm$NOR, aes(color = "5"), shape = 16, size = 4) +
		geom_point(data = reg_lm, aes(color = "1"), shape = 24, size = 5, fill = "black") +
		geom_point(data = log_lm, aes(color = "2"), shape = 15, size = 5) +
		scale_color_manual(labels = labels, values = colors) +
		guides(color = guide_legend(override.aes = list(shape = shapes))) +
		labs(x = x_label, y = y_label, color = "Legend") +
		coord_fixed(ratio = 2, xlim = c(-0.7, 0.7), ylim = c(0, 0.7))

	# Add the theme
	p1 <- add_theme(add_scales(p1))

	# If the metric is l-distance or l-kurtosis, draw a line to show the distance
	if (metric == "L-distance" | metric == "L-kurtosis") {

		# Get the sample point with the shortest distance from a distribution
		point <- if (results$recommendation %in% c("LNO", "LP3")) log_lm else reg_lm

		# Get the recommended distribbution
		df <- dlm[[results$recommendation]]

		# Get the closest point on the (t3, t4) curve (L-distance)
		if (metric == "L-distance") { 
			df$distance <- sqrt((df$x - point$x)^2 + (df$y - point$y)^2)
			df <- df[which.min(df$distance), ]
		}

		# Or get the point with the same t3 value (L-kurtosis)
		else {
			df <- df[which.min(abs(df$x - point$x)), ]
			df$distance <- abs(df$y - point$y)
		}

		# Dynamically set the radius of the magnified section
		r <- df$distance * 3

		# Draw the inset plot: same layers, zoomed to [x+-r, y+-r]
		p2 <- p1 +
			geom_segment(data = point, aes(xend = df$x, yend = df$y)) +
			coord_cartesian(
				xlim = c(point$x - r, point$x + r),
				ylim = c(point$y - r, point$y + r)
		    ) +
			theme_void() + 
			theme(
				legend.position = "none",
				panel.border = element_rect(colour = "black", fill = NA, linewidth = 1),
				plot.background = element_rect(colour = NA, fill = "white")
			)

		# Turn the inset plot into a grob
		pdf(nullfile())
		p2_grob <- ggplotGrob(p2)

		# Place inset on main plot using annotation_custom()
		p1 <- p1 +
			geom_segment(data = point, aes(xend = 0.25, yend = 0.35)) +
			geom_segment(data = point, aes(xend = -0.25, yend = 0.35)) +
		    annotation_custom(
				grob = p2_grob,
				xmin = -0.25, 
				xmax = 0.25,
				ymin = 0.35, 
				ymax = 0.60
			)

	}

	# Return the plot
	p1

}
