#' Plot Mann–Kendall–Sneyers (MKS) Test Results
#'
#' @description
#' Constructs a two‐panel visualization of the MKS test. The upper panel plots the 
#' normalized progressive and regressive Mann–Kendall S‐statistics over time, with 
#' dashed confidence bounds and potential trend‐change points. The lower panel 
#' contains the annual maximum streamflow (AMS) data with the change points highlighted
#' points along with an optional trend line.
#'
#' @param data Numeric; a vector of annual maximum streamflow data.
#'
#' @param years Numeric; a vector of years with the same length as `data`.
#'
#' @param results List; results of the MKS test, generated by \link{mks.test}.
#'
#' @param show_trend Logical; if TRUE (default), draw a fitted line through the AMS data.
#'
#' @return \code{patchwork}; A plot object with two \code{ggplot2} panels stacked vertically.
#'
#' @examples
#' data <- rnorm(n = 100, mean = 100, sd = 10)
#' years <- seq(from = 1901, to = 2000)
#' results <- mks.test(data, years)
#' mks.plot(data, years, results)
#'
#' @seealso \link{mks.test}
#'
#' @import ggplot2
#' @import patchwork
#' @export

mks.plot <- function(data, years, results, show_trend = TRUE) {

	# Create a dataframe for the bounds
	bound_df <- data.frame(y = c(-results$bound, results$bound))

	# Create the plotting dataframe
	df <- data.frame(
		max = data,
		year = years,
		s.progressive = results$s.progressive,
		s.regressive = results$s.regressive
	)

	# Define labels for the plot 
	ut_label <- "Normalized Trend Statistic"
	flow_label <- expression(AMS ~ m^3/s)
	series_labels <- c("Progressive Series", "Regressive Series")

	# Plot the normalized trend statistics and confidence bands
	p1 <- ggplot(df, aes(x = .data$year)) +
		geom_line(aes(color = "black", y = .data$s.progressive), linewidth = 1.2) +
		geom_line(aes(color = "gray",  y = .data$s.regressive), linewidth = 1.2) +
		geom_hline(
			data = bound_df,
			aes(yintercept = .data$y, color = "red"),
			linewidth = 1.2,
			linetype = "dashed",
		) +
		geom_point(
			data = results$change.df,
			aes(x =.data$years, y = .data$statistic, color = "blue"), 
			size = 4
		) +
		labs(
			title = "Mann-Kendall-Sneyers Test",
			x = "Year",
			y = ut_label,
			color = "Legend"
		) +
		scale_color_manual(
			values = c("black" = "black","gray" = "gray","blue" = "blue","red" = "red"),
			breaks = c("black", "gray", "red", "blue"),
			labels = c(series_labels, "Confidence Bounds", "Potential Trend Change")
		)

	# Plot the change points on the original dataset
	p2 <- ggplot(df, aes(x = .data$year, y = .data$max)) +
		geom_point(aes(color = "black"), size = 2.25) +
		(if (show_trend) geom_line(color = "black", linewidth = 1.1) else NULL) +
		geom_point(
			data = results$change.df,
			aes(x = .data$years, y = .data$max, color = "blue"), 
			size = 4
		) +
		labs(x = "Year", y = flow_label, color = "Legend") +
		scale_color_manual(
			values = c("black" = "black", "blue" = "blue"),
			breaks = c("black", "blue"),
			labels = c(flow_label, "Potential Trend Change")
		)	

	# Stack plots on top of each other and return
	add_theme(add_scales(p1)) / add_theme(add_scales(p2))
	
}
