#' Plot Results from the Mann–Kendall–Sneyers (MKS) Test
#'
#' @description
#' Constructs a two‐panel visualization of the MKS test:
#' 1. Upper panel: normalized progressive and regressive Mann–Kendall S‐statistics
#'    over time, with dashed confidence bounds and marked potential trend‐change points.
#' 2. Lower panel: the original annual maximum series (AMS) with optional trend line
#'    and highlighted change points.
#'
#' @param df A \code{data.frame} containing at least the following columns:
#'   \describe{
#'     \item{\code{year}}{Numeric or integer vector of years.}
#'     \item{\code{max}}{Numeric vector of observed annual maxima.}
#'   }
#'   After loading \code{result} into the environment, the function adds:
#'   \itemize{
#'     \item \code{s.progressive}: normalized progressive S‐statistic (numeric).
#'     \item \code{s.regressive}: normalized regressive S‐statistic (numeric).
#'   }
#' @param result A \code{list} containing the MKS test outputs, generated by \code{\link{mks.test}}.
#' @param show_trend Logical; if \code{TRUE} (default), draw a fitted line through the AMS series.
#'
#' @return A \code{patchwork} object stacking two \code{ggplot2} panels vertically:
#'   the test–statistic time series with bounds and change points, and the AMS series
#'   with optional trend.
#'
#' @details
#' - The upper plot uses \code{geom_line()} for S‐statistics, \code{geom_hline()}
#'   for +/-\code{bound}, and \code{geom_point()} for \code{change.df$statistic}.  
#' - The lower plot marks all AMS points with \code{geom_point()}, overlays a trend line
#'   if \code{show_trend = TRUE}, and highlights change points from \code{change.df}.  
#' - Both panels share a common color legend, with custom labels.
#'
#' @import ggplot2
#' @import patchwork
#' @export

mks.plot <- function(df, result, show_trend = TRUE) {

	# Create a dataframe for the bounds
	bound_df <- data.frame(y = c(-result$bound, result$bound))

	# Add the test statistics to df
	df$s.progressive = result$s.progressive
	df$s.regressive = result$s.regressive

	# Define labels for the plot 
	ut_label <- "Normalized Trend Statistic"
	flow_label <- expression(AMS ~ m^3/s)
	series_labels <- c("Progressive Series", "Regressive Series")

	# Plot the normalized trend statistics and confidence bands
	p1 <- ggplot(df, aes(x = .data$year)) +
		geom_line(aes(color = "black", y = .data$s.progressive), linewidth = 1.2) +
		geom_line(aes(color = "gray",  y = .data$s.regressive), linewidth = 1.2) +
		geom_hline(
			data = bound_df,
			aes(yintercept = .data$y, color = "red"),
			linewidth = 1.2,
			linetype = "dashed",
		) +
		geom_point(
			data = result$change.df,
			aes(y = .data$statistic, color = "blue"), 
			size = 4
		) +
		labs(
			title = "Mann-Kendall-Sneyers Test",
			x = "Year",
			y = ut_label,
			color = "Legend"
		) +
		scale_color_manual(
			values = c("black" = "black","gray" = "gray","blue" = "blue","red" = "red"),
			breaks = c("black", "gray", "red", "blue"),
			labels = c(series_labels, "Confidence Bounds", "Potential Trend Change")
		)

	# Plot the change points on the original dataset
	p2 <- ggplot(df, aes(x = .data$year, y = max)) +
		geom_point(aes(color = "black"), size = 2.25) +
		(if (show_trend) geom_line(color = "black", linewidth = 1.1) else NULL) +
		geom_point(data = result$change.df, aes(y = max, color = "blue"), size = 4) +
		labs(x = "Year", y = flow_label, color = "Legend") +
		scale_color_manual(
			values = c("black" = "black", "blue" = "blue"),
			breaks = c("black", "blue"),
			labels = c(flow_label, "Potential Trend Change")
		)	

	# Stack plots on top of each other and return
	add_theme(add_scales(p1)) / add_theme(add_scales(p2))
	
}
