#' Plot Return Levels and Confidence Intervals
#'
#' Constructs a time–series plot of estimated return levels along with their 
#' associated confidence intervals. The confidence bounds are shown as a shaded ribbon,
#' and the point estimates are overlaid as a solid line. The return periods are 
#' displayed on a logarithmic scale.
#'
#' If the specified model is non-stationary, the `slice` argument is required
#' and the return levels are reported as "Effective Return Periods". 
#'
#' @param results A list of estimated return levels and confidence intervals
#' generated by \link{uncertainty_bootstrap} or \link{uncertainty_rfpl}.
#'
#' @param ... Optional named arguments: 'title', 'xlabel', and 'ylabel'.
#'
#' @return `ggplot`; a plot showing:
#' - A dashed black line for both the lower and upper confidence bounds.
#' - A semi-transparent gray ribbon between `results$ci_lower` and `results$ci_upper`.
#' - A solid blue line for the point estimates.
#'
#' @examples
#' data <- rnorm(n = 100, mean = 100, sd = 10)
#' years <- seq(from = 1901, to = 2000)
#' results <- uncertainty_bootstrap(data, "WEI", "L-moments")
#' plot_uncertainty(results)
#'
#' @import ggplot2
#' @export

plot_uncertainty <- function(results, ...) {

	# Create a dataframe for the results
	df <- data.frame(
		t = results$t,
		ci_lower = results$ci_lower,
		ci_upper = results$ci_upper,
		estimates = results$estimates
	)

	# Capture optional arguments
	args <- list(...)

	# Define labels for the plot 
	title <- "FFA Estimates and Uncertainty"

	xlabel <- if (results$trend$location || results$trend$scale) {
		sprintf("Effective Return Period in %s", results$slice)
	} else { 
		"Return Period (Years)" 
	}

	ylabel <- expression("AMS (" * m^3/s * ")")

    # Override defaults if provided
    if (!is.null(args$title))  title  <- args$title
    if (!is.null(args$xlabel)) xlabel <- args$xlabel
    if (!is.null(args$ylabel)) ylabel <- args$ylabel

	# Define properties for the legend
	labels <- c("Confidence Bounds", "Estimates")
	styles <- c("dashed", "solid")

	# Generate the plot, adding the theme without plot-theme.R
	p1 <- ggplot(data = df, aes(x = t)) +
		geom_line(
			aes(y = .data$ci_lower, linetype = "1"),
			color = "black",
			linewidth = 1
		) + 
		geom_line(
			aes(y = .data$ci_upper, linetype = "1"),
			color = "black",
			linewidth = 1
		) + 
		geom_ribbon(
			aes(ymin = .data$ci_lower, ymax = .data$ci_upper),
			fill = "gray",
			alpha = 0.4
		) +
		geom_line(
			aes(y = .data$estimates, linetype = "2"),
			color = "blue",
			linewidth = 1
		) +
		scale_linetype_manual(labels = labels, values = styles) +
		labs(title = title, x = xlabel, y = ylabel, linetype = "Legend") + 
		scale_x_log10(breaks = df$t)

	# Add the theme and return 
	add_theme(p1)

}
