#' Plot Runs Test Results
#'
#' @description
#' Generates a residual plot of Sen’s estimator applied to annual maximum streamflow
#' (AMS) data with a horizontal dashed line at zero and an annotation of the Runs 
#' test .
#'
#' @param results A list of runs test results generated by \link{eda_runs_test}.
#'
#' @param type A character scalar representing whether Sen's trend estimator was  
#' applied directly to the AMS data (`"mean"`) or to the moving-window variance 
#' of the data (`"variance"`). Must be either `"variance"` or `"mean"`.
#'
#' @param ... Optional named arguments: 'title', 'xlabel', and 'ylabel'.
#'
#' @return `ggplot`; a plot containing:
#' - Black points for the residual at each year.
#' - A red dashed horizontal line at \eqn{y = 0}.
#' - A text annotation “Runs : X.XXX” in the plot area.
#'
#' @seealso \link{eda_runs_test}
#'
#' @examples
#' # Initialize data and years
#' data <- rnorm(n = 100, mean = 100, sd = 10)
#' years <- seq(from = 1901, to = 2000)
#'
#' # Generate runs test plot 
#' sens <- eda_sens_trend(data, years)
#' results <- eda_runs_test(sens)
#' plot_runs_test(results, "mean")
#'
#' @import ggplot2
#' @importFrom grid textGrob grobTree rectGrob gpar
#' @export

plot_runs_test <- function(results, type, ...) {

	# Set labels and data based on the name
	if (type == "variance") {
		title <- "Sen's Estimator Residuals (AMS Variance)"
	} else if (type == "mean") {
		title <- "Sen's Estimator Residuals (AMS Mean)"
	} else {
		stop("'type' must be either 'mean' or 'variance'")	
	}

	# Generate dataframes for the trend estimate, data, and residuals
	df_residuals <- data.frame(x = results$years, y = results$residuals)

	# Capture optional arguments
	args <- list(...)

    # Set default values
    title <- args$title %||% "Residual Plot"
    xlabel <- args$xlabel %||% "Year"
    ylabel <- args$ylabel %||% "Residual Value"

	# First subplot: Plot of residuals
	p1 <- ggplot(df_residuals, aes(x = .data$x, y = .data$y)) +
		geom_point(color = "black", size = 2.25) + 
	    geom_hline(yintercept = 0, color = "red", linetype = "dashed", linewidth = 1.2) +
		labs(title = title, x = xlabel, y = ylabel)

	# Add  annotation
	runs_label <- sprintf("Runs p-value: %.3f", results$p_value)
	p1 <- add_annotation(p1, runs_label)

	# Return the plot with added theme
	add_theme(add_scales(p1))

}

 
