#' Plot Return Levels and Confidence Intervals for S-FFA
#'
#' Constructs a time–series plot of estimated return levels along with their 
#' associated confidence intervals. The confidence bounds are shown as a shaded ribbon,
#' and the point estimates are overlaid as a solid line. The return periods are 
#' displayed on a logarithmic scale.
#'
#' If the specified model is non-stationary, the `slice` argument is required
#' and the return levels are reported as "Effective Return Periods". 
#'
#' @param results A list of estimated return levels and confidence intervals
#' generated by \link{uncertainty_bootstrap} or \link{uncertainty_rfpl}.
#'
#' @param ... Optional named arguments: 'title', 'xlabel', and 'ylabel'.
#'
#' @return `ggplot`; a plot showing:
#' - A dashed black line for both the lower and upper confidence bounds.
#' - A semi-transparent gray ribbon between `results$ci_lower` and `results$ci_upper`.
#' - A solid blue line for the point estimates.
#'
#' @examples
#' data <- rnorm(n = 100, mean = 100, sd = 10)
#' years <- seq(from = 1901, to = 2000)
#' results <- uncertainty_bootstrap(data, "WEI", "L-moments")
#' plot_sffa(results)
#'
#' @import ggplot2
#' @export

plot_sffa <- function(results, ...) {

	# Capture optional arguments
	args <- list(...)

	# Define labels for the plot, overriding if args are provided
	title <- args$title %||% "S-FFA Results"
	xlabel <- args$xlabel %||% "Return Period (Years)" 
	ylabel <- args$ylabel %||% expression("AMS (" * m^3/s * ")")

	# Define labels and styles for the legend
	labels <- c("Estimates", "Confidence Bounds")
	colors <- c("black", NA)

	# Get the first and only slice for SFFA
	results <- results[[1]]

	# Create a dataframe for the return levels
	df <- data.frame(
		periods = results$periods,
		ci_lower = results$ci_lower,
		ci_upper = results$ci_upper,
		estimates = results$estimates
	)

	# Add the lines and ribbons
	p1 <- ggplot(data = df, aes(x = .data$periods)) +
		geom_line(
			aes(y = .data$estimates, color = "1"),
			linewidth = 1
		) +
		geom_ribbon(
			aes(ymin = .data$ci_lower, ymax = .data$ci_upper, color = "2"),
			linewidth = 0,
			alpha = 0.2
		) +
		scale_color_manual(labels = labels, values = colors) +
		labs(title = title, x = xlabel, y = ylabel, linetype = "Legend") + 
		scale_x_log10(breaks = df$periods)

	# Add the theme and return 
	add_theme(p1)

}
