#' Plot Spearman’s Rho Autocorrelation
#'
#' @description
#' Visualizes Spearman’s rho autocorrelation coefficients with
#' shaded points indicating statistical significance.
#'
#' @param results List; autocorrelation coefficients generated by \link{eda_spearman_test}.
#'
#' @return `ggplot`; a plot showing:
#' - Vertical segments from \eqn{y=0} up to each \eqn{\rho} value at its lag.
#' - Filled circles at each lag, filled black if serial correlation is detected.
#'
#' @examples
#' data <- rnorm(n = 100, mean = 100, sd = 10)
#' results <- eda_spearman_test(data)
#' spearman.plot(results)
#'
#' @import ggplot2
#' @export

spearman.plot <- function(results) {

	# Create dataframe for generating the results
	rho_df <- data.frame(
		lag = 1:length(results$rho),
		rho = results$rho,
		sig = results$sig
	)

	# First subplot: Spearman's Rho Autocorrelation
	p1 <- ggplot(rho_df, aes(x = .data$lag, y = .data$rho)) +
		geom_segment(
			aes(x = .data$lag, xend = .data$lag, y = 0, yend = .data$rho)
		) +
		geom_point(
			aes(fill = .data$sig),
			shape = 21,
			size = 3,
			stroke = 1.2
		) +
		labs(
			title = "Spearman's Rho Autocorrelation",
			x = "Lag",
			y = "Spearman's Rho",
			fill = "Legend"
		) + 
		scale_fill_manual(
			values = c(`TRUE` = "black", `FALSE` = "white"),
			labels = c("No Serial Correlation", "Serial Correlation"),
		)

	# Return the plot with added theme
	add.theme(add.scales(p1))

}

 
