#' Plot Model Assessment Results
#'
#' Creates a quantile–quantile plot comparing observed annual maximum series
#' data to quantile estimates from a fitted parametric model. The 1:1 line is drawn in 
#' black and the parametric model estimates are plotted as semi‐transparent red points.
#'
#' @param results List; model assessment results generated by [model_assessment()].
#'
#' @param ... Optional named arguments: 'title', 'xlabel', and 'ylabel'.
#'
#' @return \code{ggplot}; a plot containing:
#' - A black line representing a model with no deviation from the empirical quantiles.
#' - Red points denoting the estimated quantiles against the empirical quantiles.
#'
#' @examples
#' # Initialize example data and params
#' data <- rnorm(n = 100, mean = 100, sd = 10)
#' params <- c(100, 10)
#'
#' # Perform uncertainty analysis
#' uncertainty <- uncertainty_bootstrap(data, "NOR", "L-moments")
#'
#' # Evaluate model diagnostics
#' results <- model_assessment(data, "NOR", params, ci = uncertainty$ci)
#'
#' # Generate a model assessment plot
#' plot_model_assessment(results)
#'
#' @import ggplot2
#' @export

plot_model_assessment <- function(results, ...) {

	# Create a dataframe for the plot
	x <- results$data[order(results$data, decreasing = TRUE)]   
	df <- data.frame(x = x, y = x, estimates = results$estimates) 

	# Capture optional arguments
	args <- list(...)

    # Set default values, overriding if necessary
    title <- args$title %||% "Model Diagnostics"
    xlabel <- args$xlabel %||% expression(Model ~ Quantiles ~ m^3/s)
	ylabel <- args$ylabel %||% expression(Observed ~ Quantiles ~ m^3/s)

	# Generate the plot
	p1 <- ggplot(data = df) +
		geom_line(
			aes(x = x, y = .data$y),
			linewidth = 1.1
		) + 
		geom_point(
			aes(x = x, y = .data$estimates), 
			color = "red",
			size = 3,
			alpha = 0.5
		) + 
		labs(
			title = title,
			x = xlabel,
			y = ylabel
		)

	# Add theme and scales and return
	add_theme(add_scales(p1))

}
