#' Plot Runs Test Results
#'
#' @description
#' Generates a residual plot of Sen’s estimator applied to annual maximum streamflow
#' (AMS) data with a horizontal dashed line at zero and an annotation of the Runs 
#' test p-value.
#'
#' @param years Numeric; a vector of years with the same length as `data`.
#'
#' @param results List; runs test results generated by \link{eda_runs_test}.
#'
#' @param type Character; either `"variance"` or `"mean"`.
#'
#' @param show_trend Logical; if TRUE (default), draw a fitted line through the AMS data.
#'
#' @return `ggplot`; a plot containing:
#' - Black points for the residual at each year.
#' - A red dashed horizontal line at \eqn{y = 0}.
#' - A text annotation “Runs p-value: X.XXX” in the plot area.
#'
#' @seealso \link{eda_runs_test}
#'
#' @examples
#' # Initialize data and years
#' data <- rnorm(n = 100, mean = 100, sd = 10)
#' years <- seq(from = 1901, to = 2000)
#'
#' # Generate runs test plot 
#' residuals <- eda_sens_trend(data, years)$residuals
#' results <- eda_runs_test(residuals)
#' runs.plot(years, results, "sens-mean")
#'
#' @import ggplot2
#' @importFrom grid textGrob grobTree rectGrob gpar
#' @export

runs.plot <- function(years, results, type) {

	# Run parameter validation (see helpers.R)
	validate.years(years)

	# Set labels and data based on the name
	if (type == "variance") {
		title <- "Sen's Estimator Residuals (AMS Variance)"
	} else {
		title <- "Sen's Estimator Residuals (AMS Mean)"
	}

	# Generate dataframes for the trend estimate, data, and residuals
	df_residuals <- data.frame(x = years, y = results$residuals)

	# First subplot: Plot of residuals
	p1 <- ggplot(df_residuals, aes(x = .data$x, y = .data$y)) +
		geom_point(color = "black", size = 2.25) + 
	    geom_hline(yintercept = 0, color = "red", linetype = "dashed", linewidth = 1.2) +
		labs(title = "Residual Plot", x = "Year", y = "Residual Value")

	# Add p-value annotation
	runs_label <- sprintf("Runs p-value: %.3f", results$p.value)
	p1 <- add.annotation(p1, runs_label)

	# Return the plot with added theme
	add.theme(add.scales(p1))

}

 
