#' Plot Return Levels and Confidence Intervals
#'
#' @description
#' Constructs a time–series plot of estimated return levels along with their 
#' associated confidence intervals. The confidence bounds are shown as a shaded ribbon,
#' and the point estimates are overlaid as a solid line. The return periods are 
#' displayed on a logarithmic scale.
#'
#' If the specified model is non-stationary, the `slice` argument is required
#' and the return levels are reported as "Effective Return Periods". 
#'
#' @param results List; generated by \link{sb.uncertainty} or \link{rfpl.uncertainty}.
#'
#' @param trend List; information about non-stationary trend(s) to use:
#' - `location` Logical (1); if TRUE, there is a trend in the location parameter.
#' - `scale` Logical (1); if TRUE, there is a trend in the scale parameter.
#'
#' @param slice Character (1); the anchor year for non-stationary return level estimates.
#'   Required for models ending in `10`, `100`, `11`, or `110`.
#'
#' @return `ggplot`; a plot showing:
#' - A dashed black line for both the lower and upper confidence bounds.
#' - A semi-transparent gray ribbon between `results$ci_lower` and `results$ci_upper`.
#' - A solid blue line for the point estimates.
#'
#' @examples
#' data <- rnorm(n = 100, mean = 100, sd = 10)
#' years <- seq(from = 1901, to = 2000)
#' results <- sb.uncertainty(data, years, "WEI", "L-moments")
#' uncertainty.plot("WEI", results)
#'
#' @import ggplot2
#' @export

uncertainty.plot <- function(results, trend, slice = NULL) {

	# Set slice to the first result for S-FFA
	if (is.null(slice)) slice = 1

	# Create a dataframe for the results
	df <- data.frame(
		t = results[[slice]]$t,
		ci_lower = results[[slice]]$ci_lower,
		ci_upper = results[[slice]]$ci_upper,
		estimates = results[[slice]]$estimates
	)

	# Define labels for the plot 
	x_label <- if (trend$location || trend$scale) {
		sprintf("Effective Return Period in %s", slice)
	} else { 
		"Return Period (Years)" 
	}

	y_label <- expression("AMS (" * m^3/s * ")")

	# Define properties for the legend
	labels <- c("Confidence Bounds", "Estimates")
	styles <- c("dashed", "solid")

	# Generate the plot, adding the theme without plot-theme.R
	p1 <- ggplot(data = df, aes(x = t)) +
		geom_line(
			aes(y = .data$ci_lower, linetype = "1"),
			color = "black",
			linewidth = 1
		) + 
		geom_line(
			aes(y = .data$ci_upper, linetype = "1"),
			color = "black",
			linewidth = 1
		) + 
		geom_ribbon(
			aes(ymin = .data$ci_lower, ymax = .data$ci_upper),
			fill = "gray",
			alpha = 0.4
		) +
		geom_line(
			aes(y = .data$estimates, linetype = "2"),
			color = "blue",
			linewidth = 1
		) +
		scale_linetype_manual(labels = labels, values = styles) +
		labs(
			x = x_label,
			y = y_label,
			linetype = "Legend",
			title = "FFA Estimates and Uncertainty"
		) +
		scale_x_log10(breaks = df$t)

	# Add the theme and return 
	add.theme(p1)

}
