#' Plot Model Assessment Results
#'
#' @description
#' Creates a quantile–quantile plot comparing observed annual maximum streamflow (AMS)
#' data to quantile estimates from a fitted parametric model. The 1:1 line is drawn in 
#' black and the model estimates are plotted as semi‐transparent red points.
#'
#' @param results List; model assessment results generated by \link{model_diagnostics}.
#'
#' @param ... Optional named arguments: 'title', 'xlabel', and 'ylabel'.
#'
#' @return \code{ggplot}; a plot containing:
#' - A black line representing a perfect model with no deviation from the data.
#' - Red points marking the estimated quantiles against the observed quantiles.
#'
#' @examples
#' # Initialize example data and params
#' data <- rnorm(n = 100, mean = 100, sd = 10)
#' params <- c(100, 10)
#'
#' # Perform uncertainty analysis
#' uncertainty <- uncertainty_bootstrap(data, "NOR", "L-moments")
#'
#' # Evaluate model diagnostics
#' results <- model_diagnostics(data, "NOR", params, uncertainty)
#'
#' # Generate a model assessment plot
#' plot_model_diagnostics(results)
#'
#' @import ggplot2
#' @export

plot_model_diagnostics <- function(results, ...) {

	data <- validate_data(results$data)

	# Create a dataframe for the plot
	x <- data[order(data, decreasing = TRUE)]   
	df <- data.frame(x = x, y = x, estimates = results$estimates) 

	# Get labels for the plot

	# Capture optional arguments
	args <- list(...)

    # Set default values
    title <- "Model Assessment"
    xlabel <- expression(Model ~ Quantiles ~ m^3/s)
	ylabel <- expression(Observed ~ Quantiles ~ m^3/s)

    # Override defaults if provided
    if (!is.null(args$title))  title  <- args$title
    if (!is.null(args$xlabel)) xlabel <- args$xlabel
    if (!is.null(args$ylabel)) ylabel <- args$ylabel

	# Generate the plot
	p1 <- ggplot(data = df) +
		geom_line(
			aes(x = x, y = .data$y),
			linewidth = 1.1
		) + 
		geom_point(
			aes(x = x, y = .data$estimates), 
			color = "red",
			size = 3,
			alpha = 0.5
		) + 
		labs(
			title = title,
			x = xlabel,
			y = ylabel
		)

	# Add theme and scales and return
	add_theme(add_scales(p1))

}
