#' Plot Results from the Pettitt Change‐Point Test
#'
#' @description
#' Creates a two‐panel visualization of the Mann–Whitney–Pettitt test. The 
#' upper panel plots the Pettitt \eqn{U_t} statistic over time along with the 
#' significance threshold and potential change point. The lower panel displays 
#' the annual maximum streamflow (AMS) data with an optional trend line, 
#' estimates of the mean, and potential change point.
#'
#' @param results A list generated by \link{eda_pettitt_test}.
#'
#' @param show_trend If `TRUE` (default), draw a fitted line through the AMS data.
#'
#' @param ... Optional named arguments: 'title', 'top_xlabel', 'top_ylabel', 
#'   'bottom_xlabel' and 'bottom_ylabel'.
#'
#' @return A \code{patchwork} object with two \code{ggplot2} panels stacked vertically.
#'
#' @examples
#' data <- rnorm(n = 100, mean = 100, sd = 10)
#' years <- seq(from = 1901, to = 2000)
#' results <- eda_pettitt_test(data, years)
#' plot_pettitt_test(results)
#'
#' @seealso \link{eda_pettitt_test}
#'
#' @import ggplot2
#' @import patchwork
#' @export

plot_pettitt_test <- function(results, show_trend = TRUE, ...) {

	data <- validate_data(results$data)
	years <- validate_years(results$years)

	# Add u_t to df and create change point df (if change point is significant)
	df <- data.frame(
		max = data,
		year = years,
		u_t = results$u_t
	)

	change_df <- df[results$change_index, ]

	# Get the segment endpoints depending on whether there is a change point
	n <- length(results$u_t)
	ends <- if (results$change_index == 0) c(1, n) else c(1, results$change_index, n) 

	n_ends <- length(ends)
	get_segment_mean <- function(i) mean(df$max[ends[i]:ends[i + 1]])

	# Compute the segment means for the plot
	segment_df <- data.frame(
		x = df$year[ends[-n_ends]],            
		xend = df$year[ends[-1]],
		y = sapply(1:(n_ends - 1), get_segment_mean)
	)

	# Capture optional arguments
	args <- list(...)

	# Define labels for the plot 
    title <- "Mann-Whitney-Pettitt Test"
	top_xlabel <- "Year" 
	top_ylabel <- expression(U[t] ~ Statistic)
	bottom_xlabel <- "Year" 
	bottom_ylabel <- expression(AMS ~ m^3/s)

    # Override defaults if provided
    if (!is.null(args$title))  title  <- args$title
    if (!is.null(args$top_xlabel)) top_xlabel <- args$top_xlabel
    if (!is.null(args$top_ylabel)) top_ylabel <- args$top_ylabel
    if (!is.null(args$bottom_xlabel)) top_xlabel <- args$top_xlabel
    if (!is.null(args$bottom_ylabel)) top_ylabel <- args$top_ylabel

	# First subplot: Mann-Whitney-Pettitt Test
	p1 <- ggplot(df, aes(x = .data$year, y = .data$u_t)) +
		geom_line(aes(color = "black"), linewidth = 1.2) +
		geom_hline(
			aes(yintercept = results$k_critical, color = "red"),
			linewidth = 1.2,
			linetype = "dashed",
		) +
		geom_point(data = change_df, aes(color = "blue"), size = 4) +
		labs(title = title, x = top_xlabel, y = top_ylabel, color = "Legend") + 
		scale_color_manual(
			values = c("black" = "black", "red" = "red", "blue" = "blue"),
			breaks = c("black", "red", "blue"),
			labels = c(top_ylabel, "Change Point Threshold", "Potential Change Point")
		)
		
	# Also plot the original flow data and segment means
	p2 <- ggplot(df, aes(x = .data$year, y = max)) +
		geom_point(aes(color = "black"), size = 2.25) +
		(if (show_trend) geom_line(color = "black", linewidth = 1.1) else NULL) + 
		geom_segment(
			data = segment_df, 
			aes(x = .data$x, xend = .data$xend, y = .data$y, color = "green4"),
			linewidth = 1.2 
		) + 
		geom_point(data = change_df, aes(color = "blue"), size = 4) +
		labs(x = bottom_xlabel, y = bottom_ylabel, color = "Legend") +
		scale_color_manual(
			values = c("black" = "black", "green4" = "green4", "blue" = "blue"),
			breaks = c("black", "green4", "blue"),
			labels = c(bottom_ylabel, "Segment Mean(s)", "Potential Change Point")
		)	

	# Stack plots on top of each other and return
	add_theme(add_scales(p1)) / add_theme(add_scales(p2))

}
