#' Plot Results from the Pettitt Change‐Point Test
#'
#' @description
#' Creates a two‐panel visualization of the Mann–Whitney–Pettitt test. The 
#' upper panel plots the Pettitt \eqn{U_t} statistic over time along with the 
#' significance threshold and potential change point. The lower panel displays 
#' the annual maximum streamflow (AMS) data with an optional trend line, 
#' estimates of the mean, and potential change point.
#'
#' @param data Numeric; a vector of annual maximum streamflow data.
#'
#' @param years Numeric; a vector of years with the same length as `data`.
#'
#' @param results List; results of the Pettitt test, generated by \link{eda_pettitt_test}.
#'
#' @param show_trend Logical; if TRUE (default), draw a fitted line through the AMS data.
#'
#' @return \code{patchwork}; A plot object with two \code{ggplot2} panels stacked vertically.
#'
#' @examples
#' data <- rnorm(n = 100, mean = 100, sd = 10)
#' years <- seq(from = 1901, to = 2000)
#' results <- eda_pettitt_test(data, years)
#' pettitt.plot(data, years, results)
#'
#' @seealso \link{eda_pettitt_test}
#'
#' @import ggplot2
#' @import patchwork
#' @export

pettitt.plot <- function(data, years, results, show_trend = TRUE) {

	# Run parameter validation (see helpers.R)
	validate.data(data)
	validate.years(years)

	# Add ut to df and create change point df (if change point is significant)
	df <- data.frame(
		max = data,
		year = years,
		ut = results$ut
	)

	change_df <- df[results$change.index, ]

	# Get the segment endpoints depending on whether there is a change point
	n <- length(results$ut)
	ends <- if (results$change.index == 0) c(1, n) else c(1, results$change.index, n) 

	n_ends <- length(ends)
	get_segment_mean <- function(i) mean(df$max[ends[i]:ends[i + 1]])

	# Compute the segment means for the plot
	segment_df <- data.frame(
		x = df$year[ends[-n_ends]],            
		xend = df$year[ends[-1]],
		y = sapply(1:(n_ends - 1), get_segment_mean)
	)

	# Generate the labels with proper formatting
	ut_label <- expression(U[t] ~ Statistic)
	flow_label <- expression(AMS ~ m^3/s)

	# First subplot: Mann-Whitney-Pettitt Test
	p1 <- ggplot(df, aes(x = .data$year, y = .data$ut)) +
		geom_line(aes(color = "black"), linewidth = 1.2) +
		geom_hline(
			aes(yintercept = results$k.critical, color = "red"),
			linewidth = 1.2,
			linetype = "dashed",
		) +
		geom_point(data = change_df, aes(color = "blue"), size = 4) +
		labs(
			title = "Mann-Whitney-Pettitt Test",
			x = "Year",
			y = ut_label,
			color = "Legend") +
		scale_color_manual(
			values = c("black" = "black", "red" = "red", "blue" = "blue"),
			breaks = c("black", "red", "blue"),
			labels = c(ut_label, "Change Point Threshold", "Potential Change Point")
		)
		
	# Also plot the original flow data and segment means
	p2 <- ggplot(df, aes(x = .data$year, y = max)) +
		geom_point(aes(color = "black"), size = 2.25) +
		(if (show_trend) geom_line(color = "black", linewidth = 1.1) else NULL) + 
		geom_segment(
			data = segment_df, 
			aes(x = .data$x, xend = .data$xend, y = .data$y, color = "green4"),
			linewidth = 1.2 
		) + 
		geom_point(data = change_df, aes(color = "blue"), size = 4) +
		labs(x = "Year", y = flow_label, color = "Legend") +
		scale_color_manual(
			values = c("black" = "black", "green4" = "green4", "blue" = "blue"),
			breaks = c("black", "green4", "blue"),
			labels = c(flow_label, "Segment Mean(s)", "Potential Change Point")
		)	

	# Stack plots on top of each other and return
	add.theme(add.scales(p1)) / add.theme(add.scales(p2))

}
