#' Plot Sen’s Trend Estimator
#'
#' @description
#' Produces a scatter plot of the annual maximum streamflow (AMS) data or its variance
#' against time, overlaid with Sen’s trend estimator and an annotation of the fitted 
#' equation.
#'
#' @param results A list of Sen's trend estimates generated by \link{eda_sens_trend}.
#'
#' @param type A character scalar representing whether Sen's trend estimator was  
#' applied directly to the AMS data (`"mean"`) or to the moving-window variance 
#' of the data (`"variance"`). Must be either `"variance"` or `"mean"`.
#'
#' @param show_trend If `TRUE` (default), draw a fitted line through the AMS data.
#'
#' @param ... Optional named arguments: 'title', 'xlabel', and 'ylabel'.
#'
#' @return `ggplot`; a plot containing:
#' - Black points for each year’s AMS (or variance) value.
#' - Optional black line connecting the AMS data if `show_trend = TRUE`.
#' - Blue line representing Sen’s trend estimator.
#' - A text annotation displaying the fitted equation \eqn{y = mx + b}.
#'
#' @seealso \link{eda_sens_trend}
#'
#' @examples
#' data <- rnorm(n = 100, mean = 100, sd = 10)
#' years <- seq(from = 1901, to = 2000)
#' results <- eda_sens_trend(data, years)
#' plot_sens_trend(results, "mean")
#'
#' @import ggplot2
#' @importFrom grid textGrob
#' @export

plot_sens_trend <- function(results, type, show_trend = TRUE, ...) {

	# Load the results of the test into the environment
	m <- results$slope
	b <- results$intercept
	equation <- sprintf("y = %.3fx + %.2f", m, b)

	# Capture optional arguments
	args <- list(...)

	# Set labels and data based on the type
	xlabel <- "Covariate"

	if (type == "variance") {
		ylabel <- expression(AMS ~ Variance ~ m^3/s)
		title <- "Sen's Trend Estimator (AMS Variance)"
	} else if (type == "mean") {
		ylabel <- expression(AMS ~ m^3/s)
		title <- "Sen's Trend Estimator (AMS Mean)"
	} else {
		stop("'type' must be either 'mean' or 'variance'")	
	}

    # Override defaults if provided
    if (!is.null(args$title))  title  <- args$title
    if (!is.null(args$xlabel)) xlabel <- args$xlabel
    if (!is.null(args$ylabel)) ylabel <- args$ylabel

	# Generate dataframes for the trend estimate, data
	covariate <- get_covariates(results$years)
	df_line <- data.frame(x = covariate, y = m * covariate + b)
	df_data <- data.frame(x = covariate, y = results$data)

	# First subplot: Plot of Sen's trend estimator
	p1 <- ggplot(df_data, aes(x = .data$x, y = .data$y)) +
		geom_point(aes(color = "black"), size = 2.25) + 
		(if (show_trend) geom_line(color = "black", linewidth = 1.1) else NULL) +
		geom_line(
			data = df_line,
			aes(x = .data$x, y = .data$y, color = "blue"),
			linewidth = 1.2
		) + 
		labs(title = title, x = xlabel, y = ylabel, color = "Legend") + 
		scale_color_manual(
			values = c("blue" = "blue", "black" = "black"),
			breaks = c("blue", "black"),
			labels = c("Estimated Trend", ylabel),
		) 

	# Add equation annotation, scales, and theme
	p1 <- add_annotation(p1, equation)
	add_theme(add_scales(p1))

}

 
