#' Plot Residuals and Runs Test p-Value for Sen’s Estimator
#'
#' @description
#' Generates a residual plot of Sen’s estimator applied to annual maximum series (AMS),
#' with a horizontal dashed line at zero and an annotation of the Runs test p-value.
#' The function can display either the residuals of the variance or the mean estimator,
#' depending on the \code{name} argument.
#'
#' @param df A \code{data.frame} containing at least:
#'   \describe{
#'     \item{\code{year}}{Numeric or integer vector of years.}
#'     \item{\code{std}}{Numeric vector of standard deviations (if \code{name = "sens-variance"}).}
#'     \item{\code{max}}{Numeric vector of observed AMS values (if \code{name = "sens-mean"}).}
#'   }
#' @param results A \code{list} generated by \code{\link{runs.test}}.
#' @param name Character; either \code{"sens-variance"} or \code{"sens-mean"}.
#' @param show_trend Logical; if \code{TRUE} (default), overlay a trend line through the AMS series.
#'
#' @return A \code{ggplot} object showing:
#'   \itemize{
#'     \item Black points for each residual versus year.
#'     \item A red dashed horizontal line at \eqn{y = 0}.
#'     \item A text annotation of “Runs p-value: X.XXX” in the plot area.
#'   }
#'
#' @seealso
#' \code{\link[ggplot2]{geom_point}}, \code{\link[ggplot2]{geom_hline}}
#'
#' @import ggplot2
#' @importFrom grid textGrob grobTree rectGrob gpar
#' @export

runs.plot <- function(df, residuals, results, name, show_trend = TRUE) {

	# Set labels and data based on the name
	if (name == "sens-variance") {
		data <- df$std
		title <- "Sen's Estimator Residuals (AMS Variance)"
	} else {
		data <- df$max
		title <- "Sen's Estimator Residuals (AMS Mean)"
	}

	# Generate dataframes for the trend estimate, data, and residuals
	df_residuals <- data.frame(x = df$year, y = residuals)

	# First subplot: Plot of residuals
	p1 <- ggplot(df_residuals, aes(x = .data$x, y = .data$y)) +
		geom_point(color = "black", size = 2.25) + 
	    geom_hline(yintercept = 0, color = "red", linetype = "dashed", linewidth = 1.2) +
		labs(title = "Residual Plot", x = "Year", y = "Residual Value")

	# Add p-value annotation
	runs_label <- sprintf("Runs p-value: %.3f", results$p.value)
	p1 <- add_annotation(p1, runs_label)

	# Return the plot with added theme
	add_theme(add_scales(p1))

}

 
