#' Plot Results from Sen’s Trend Estimator
#'
#' @description
#' Produces a scatter plot of the annual maximum series (AMS) or its variance
#' against time, overlaid with Sen’s estimated trend line and a text annotation
#' of the fitted equation.
#'
#' @param df A \code{data.frame} containing at least:
#'   \describe{
#'     \item{\code{year}}{Numeric or integer vector of observation years.}
#'     \item{\code{std}}{Numeric vector of estimated AMS variances (if \code{name = "sens-variance"}).}
#'     \item{\code{max}}{Numeric vector of observed AMS values (if \code{name = "sens-mean"}).}
#'   }
#' @param results A \code{list} generated by \code{\link{sens.trend}}.
#' @param name Character; if \code{"sens-variance"}, plots residual variance (\code{df$std})
#'   and titles the plot accordingly. If \code{"sens-mean"}, plots AMS mean (\code{df$max}).
#' @param show_trend Logical; if \code{TRUE} (default), draws the AMS data trend line.
#'
#' @return A \code{ggplot} object showing:
#'   \itemize{
#'     \item Black points for each year’s AMS (or variance) value.
#'     \item Optional black line connecting the raw data if \code{show_trend = TRUE}.
#'     \item Blue line representing Sen’s trend estimate.
#'     \item A text annotation displaying the fitted equation \eqn{y = mx + b}.
#'   }
#'
#' @import ggplot2
#' @importFrom grid textGrob
#' @export

sens.plot <- function(df, results, name, show_trend = TRUE) {

	# Load the results of the test into the environment
	m <- results$sens.slope
	b <- results$sens.intercept

	# Set labels and data based on the name
	if (name == "sens-variance") {
		data <- df$std
		ams_label <- expression(AMS ~ Variance ~ m^3/s)
		title <- "Sen's Trend Estimator (AMS Variance)"
	} else {
		data <- df$max
		ams_label <- expression(AMS ~ m^3/s)
		title <- "Sen's Trend Estimator (AMS Mean)"
	}

	# Generate dataframes for the trend estimate, data
	df_line <- data.frame(x = df$year, y = m * (df$year) + b)
	df_data <- data.frame(x = df$year, y = data)

	# Generate the equation and runs test label 
	eq_label <- sprintf("y = %.3fx + %.2f", m, b)

	# First subplot: Plot of Sen's trend estimator
	p1 <- ggplot(df_data, aes(x = .data$x, y = .data$y)) +
		geom_point(aes(color = "black"), size = 2.25) + 
		(if (show_trend) geom_line(color = "black", linewidth = 1.1) else NULL) +
		geom_line(data = df_line, aes(x = .data$x, y = .data$y, color = "blue"), linewidth = 1.2) + 
		labs(title = title, x = "Year", y = ams_label, color = "Legend") + 
		scale_color_manual(
			values = c("blue" = "blue", "black" = "black"),
			breaks = c("blue", "black"),
			labels = c("Estimated Trend", ams_label),
		) 

	# Add equation annotation, scales, and theme
	p1 <- add_annotation(p1, eq_label)
	add_theme(add_scales(p1))

}

 
