#' Plot Sen’s Trend Estimator
#'
#' @description
#' Produces a scatter plot of the annual maximum streamflow (AMS) data or its variance
#' against time, overlaid with Sen’s trend estimator and an annotation of the fitted 
#' equation.
#'
#' @param data Numeric; a vector of annual maximum streamflow data.
#'
#' @param years Numeric; a vector of years with the same length as `data`.
#'
#' @param results List; runs test results generated by \link{sens.trend}.
#'
#' @param name Character; either `"sens-variance"` or `"sens-mean"`.
#'
#' @param show_trend Logical; if TRUE (default), draw a fitted line through the AMS data.
#'
#' @return `ggplot`; a plot containing:
#' - Black points for each year’s AMS (or variance) value.
#' - Optional black line connecting the AMS data if `show_trend = TRUE`.
#' - Blue line representing Sen’s trend estimator.
#' - A text annotation displaying the fitted equation \eqn{y = mx + b}.
#'
#' @seealso \link{sens.trend}
#'
#' @examples
#' data <- rnorm(n = 100, mean = 100, sd = 10)
#' years <- seq(from = 1901, to = 2000)
#' results <- sens.trend(data, years)
#' sens.plot(data, years, results, "sens-mean")
#'
#' @import ggplot2
#' @importFrom grid textGrob
#' @export

sens.plot <- function(data, years, results, name, show_trend = TRUE) {

	# Load the results of the test into the environment
	m <- results$sens.slope
	b <- results$sens.intercept

	# Set labels and data based on the name
	if (name == "sens-variance") {
		ams_label <- expression(AMS ~ Variance ~ m^3/s)
		title <- "Sen's Trend Estimator (AMS Variance)"
	} else {
		ams_label <- expression(AMS ~ m^3/s)
		title <- "Sen's Trend Estimator (AMS Mean)"
	}

	# Generate dataframes for the trend estimate, data
	covariate <- get.covariates(years)
	df_line <- data.frame(x = covariate, y = m * covariate + b)
	df_data <- data.frame(x = covariate, y = data)

	# Generate the equation and runs test label 
	eq_label <- sprintf("y = %.3fx + %.2f", m, b)

	# First subplot: Plot of Sen's trend estimator
	p1 <- ggplot(df_data, aes(x = .data$x, y = .data$y)) +
		geom_point(aes(color = "black"), size = 2.25) + 
		(if (show_trend) geom_line(color = "black", linewidth = 1.1) else NULL) +
		geom_line(
			data = df_line,
			aes(x = .data$x, y = .data$y, color = "blue"),
			linewidth = 1.2
		) + 
		labs(title = title, x = "Covariate", y = ams_label, color = "Legend") + 
		scale_color_manual(
			values = c("blue" = "blue", "black" = "black"),
			breaks = c("blue", "black"),
			labels = c("Estimated Trend", ams_label),
		) 

	# Add equation annotation, scales, and theme
	p1 <- add_annotation(p1, eq_label)
	add_theme(add_scales(p1))

}

 
