#' Plot Spearman’s Rho Autocorrelation Results
#'
#' @description
#' Visualizes the lagged Spearman’s rho autocorrelation coefficients with stems
#' from zero and points indicating statistical significance.
#'
#' @param results A \code{list} generated by \code{\link{spearman.test}}.
#'
#' @return A \code{ggplot} object showing:
#'   \itemize{
#'     \item Vertical segments from \eqn{y=0} up to each \eqn{\rho} value at its lag.
#'     \item Filled circles at each lag, filled black if \code{sig == TRUE} (no serial correlation)
#'       or white if \code{sig == FALSE} (serial correlation detected).
#'   }
#'
#' @import ggplot2
#' @export


spearman.plot <- function(results) {

	# Create dataframe for generating the results
	rho_df <- data.frame(
		lag = 1:length(results$rho),
		rho = results$rho,
		sig = results$sig
	)

	# First subplot: Spearman's Rho Autocorrelation
	p1 <- ggplot(rho_df, aes(x = .data$lag, y = .data$rho)) +
		geom_segment(
			aes(x = .data$lag, xend = .data$lag, y = 0, yend = .data$rho)
		) +
		geom_point(
			aes(fill = .data$sig),
			shape = 21,
			size = 3,
			stroke = 1.2
		) +
		labs(
			title = "Spearman's \u03c1 Autocorrelation",
			x = "Lag",
			y = "Spearman's \u03c1",
			fill = "Legend"
		) + 
		scale_fill_manual(
			values = c(`TRUE` = "black", `FALSE` = "white"),
			labels = c("No Serial Correlation", "Serial Correlation"),
		)

	# Return the plot with added theme
	add_theme(add_scales(p1))

}

 
