#' Plot Uncertainty Bounds and Estimates Over Time
#'
#' @description
#' Constructs a time–series plot of parameter estimates with their associated
#' confidence intervals. The confidence bounds are shown as a shaded ribbon,
#' and the point estimates are overlaid as a solid line. The x-axis is displayed
#' on a log10 scale.
#'
#' @param results A \code{list} containing the uncertainty analysis output. 
#'   Generated by \code{\link{sb.uncertainty}}.
#'
#' @return A \code{ggplot} object showing:
#'   \itemize{
#'     \item A dashed black line for both the lower and upper confidence bounds.
#'     \item A gray ribbon between \code{ci_lower} and \code{ci_upper}, semi‐transparent.
#'     \item A solid blue line for the point estimates.
#'     \item A log10‐scaled x‐axis with ticks at each \code{t}.
#'   }
#'
#' @import ggplot2
#' @export

uncertainty.plot <- function(results) {

	# Create a dataframe for the results
	df <- data.frame(
		t = results[[1]]$t,
		ci_lower = results[[1]]$ci_lower,
		ci_upper = results[[1]]$ci_upper,
		estimates = results[[1]]$estimates
	)

	# Define labels for the plot 
	x_label <- "Time (Years)"
	y_label <- expression("AMS (" * m^3/s * ")")

	# Define properties for the legend
	labels <- c("Confidence Bounds", "Estimates")
	styles <- c("dashed", "solid")

	# Generate the plot, adding the theme without plot-theme.R
	p1 <- ggplot(data = df, aes(x = t)) +
		geom_line(
			aes(y = .data$ci_lower, linetype = "1"),
			color = "black",
			linewidth = 1
		) + 
		geom_line(
			aes(y = .data$ci_upper, linetype = "1"),
			color = "black",
			linewidth = 1
		) + 
		geom_ribbon(
			aes(ymin = .data$ci_lower, ymax = .data$ci_upper),
			fill = "gray",
			alpha = 0.4
		) +
		geom_line(
			aes(y = .data$estimates, linetype = "2"),
			color = "blue",
			linewidth = 1
		) +
		scale_linetype_manual(labels = labels, values = styles) +
		labs(x = x_label, y = y_label, linetype = "Legend") +
		scale_x_log10(breaks = df$t)

	# Add the theme and return 
	add_theme(p1)

}
