#' Plot Return Levels and Confidence Intervals
#'
#' @description
#' Constructs a time–series plot of estimated return levels along with their 
#' associated confidence intervals. The confidence bounds are shown as a shaded ribbon,
#' and the point estimates are overlaid as a solid line. The return periods are 
#' displayed on a logarithmic scale.
#'
#' If the specified model is non-stationary, the `slice` argument is required
#' and the return levels are reported as "Effective Return Periods". 
#'
#' @param model Character (1); string specifying the probability model. The first three 
#'   letters denote the family: `GUM`, `NOR`, `LNO`, `GEV`, `GLO`, `GNO`, `PE3`, 
#'   `LP3`, or `WEI`. A trailing signature of `10` or `100` indicates a linear trend 
#'   in location; `11` or `110` indicates linear trends in both location and scale.
#'
#' @param results List; generated by \link{sb.uncertainty} or \link{rfpl.uncertainty}.
#'
#' @param slice Character (1); the anchor year for non-stationary return level estimates.
#'   Required for models ending in `10`, `100`, `11`, or `110`.
#'
#' @return `ggplot`; a plot showing:
#' - A dashed black line for both the lower and upper confidence bounds.
#' - A semi-transparent gray ribbon between `results$ci_lower` and `results$ci_upper`.
#' - A solid blue line for the point estimates.
#'
#' @examples
#' data <- rnorm(n = 100, mean = 100, sd = 10)
#' years <- seq(from = 1901, to = 2000)
#' results <- sb.uncertainty(data, years, "WEI", "L-moments")
#' uncertainty.plot("WEI", results)
#'
#' @import ggplot2
#' @export

uncertainty.plot <- function(model, results, slice = 1) {

	# Get the name and signature for the model 
	name <- substr(model, 1, 3)
	signature <- if (nchar(model) == 3) NULL else substr(model, 4, 5)

	# Create a dataframe for the results
	df <- data.frame(
		t = results[[slice]]$t,
		ci_lower = results[[slice]]$ci_lower,
		ci_upper = results[[slice]]$ci_upper,
		estimates = results[[slice]]$estimates
	)

	# Define labels for the plot 
	x_label <- if (is.null(signature)) {
		"Return Period (Years)" 
	} else { 
		sprintf("Effective Return Period in %s", slice)
	}

	y_label <- expression("AMS (" * m^3/s * ")")

	# Define properties for the legend
	labels <- c("Confidence Bounds", "Estimates")
	styles <- c("dashed", "solid")

	# Generate the plot, adding the theme without plot-theme.R
	p1 <- ggplot(data = df, aes(x = t)) +
		geom_line(
			aes(y = .data$ci_lower, linetype = "1"),
			color = "black",
			linewidth = 1
		) + 
		geom_line(
			aes(y = .data$ci_upper, linetype = "1"),
			color = "black",
			linewidth = 1
		) + 
		geom_ribbon(
			aes(ymin = .data$ci_lower, ymax = .data$ci_upper),
			fill = "gray",
			alpha = 0.4
		) +
		geom_line(
			aes(y = .data$estimates, linetype = "2"),
			color = "blue",
			linewidth = 1
		) +
		scale_linetype_manual(labels = labels, values = styles) +
		labs(
			x = x_label,
			y = y_label,
			linetype = "Legend",
			title = "FFA Estimates and Uncertainty"
		) +
		scale_x_log10(breaks = df$t)

	# Add the theme and return 
	add_theme(p1)

}
